const scp = [
    [
        {
            id: 0,
            name: 'Сиреноголовый',
            type: 'Волна 5 Команда Укротителей',
            keeping: 'Антизвуковая установка обездвиживает его; ' +
            'при голодании начинает становиться более агрессивным и менее сосредоточенным на сокрытии своего присутствия',
            description: 'Сиреноголовый - это 40-футовый гуманоид, напоминающий обтянутый высушенной, мумифицированной плотью цвета ржавого металла скелет. Конечности существа непропорционально длинные и тонкие, руки достают до уровня икр и заканчивающиеся костлявыми кистями с длинными тонкими пальцами. ' +
            'Тело увенчано установкой с двумя развёрнутыми в противоположные друг другу стороны сиренами.',
            behavior: 'Сиреноголовый является крайне агрессивным хищником, которого можно встретить в лесу, маленьких деревнях, на полях и т.д. Наиболее распространенная охотничья тактика, используемая Сиреноголовым - это заманивание своих жертв криками о помощи, которые звучат по-человечески. ' +
            'Когда жертва приближается на достаточное расстояние он хватает её и, предположительно, разрывает на части и съедает.',
            hazard: 'Высокий',
            image: 'https://res.cloudinary.com/dv4fxot90/image/upload/v1597220238/scp_images/siren-head_pdpl9b.jpg',
            sound: 'https://res.cloudinary.com/dv4fxot90/video/upload/v1597166991/scp_sounds/siren-head_zsvhed.mp3',
        },
        {
            id: 1,
            name: 'Йо-йо',
            type: 'Волна 2 Опасные',
            keeping: 'Неизвестно',
            description: 'Выглядит как маленькая девочка с желтой медвежьей головой. ' +
                'Носит маску, поскольку все её лицо выглядит детский рисунок. ',
            behavior: 'Дарит детям отравленные подарки',
            hazard: 'Средний',
            image: 'https://res.cloudinary.com/dv4fxot90/image/upload/v1597231667/scp_images/yo-yo_q4edh4.jpg',
            sound: 'https://res.cloudinary.com/dv4fxot90/video/upload/v1597231317/scp_sounds/yo-yo_jqxi8w.mp3',
        },
        {
            id: 2,
            name: 'Мультяшный кот',
            type: 'Волна 5 Команда Укротителей',
            keeping: 'Неизвестно',
            description: 'Человекоподобный кот с чёрной шерстью, большими овальными бело-чёрыми глазами и жутким оскалом из человеческих зубов. ' +
            'Так же у Мультяшного кота длинные конечности сгибающиеся бесчисленное множество раз в любых местах.',
            behavior: 'Мультяшный кот является злейшим монстром и по совместительству самым страшным. ' +
            'Его территорию обходят другие монстры, так как боятся его.',
            hazard: 'Очень высокий',
            image: 'https://res.cloudinary.com/dv4fxot90/image/upload/v1597220245/scp_images/cartoon-cat_oefxcu.jpg',
            sound: 'https://res.cloudinary.com/dv4fxot90/video/upload/v1597169414/scp_sounds/cartoon-cat_rvl0ti.mp3',
        },
        {
            id: 3,
            name: 'Долговязая лошадь',
            type: 'Волна 0 Безвредные',
            keeping: 'Нет необходимости',
            description: 'шея Долговязая Лошади может изгибаться в любом месте, с характерным хрустом костей, который слышен при её движении, при этом имеет бесконечную длину и может расширятся. ' +
            'О теле Долговязой лошади ничего не известно: оно может представлять собой такие вещи, что мы просто не сможем воспринять.',
            behavior: 'Долговязая Лошадь появляется во сне, и своим появлением предупреждает спящего о надвигающемся несчастье.',
            hazard: 'Безопасно',
            image: 'https://res.cloudinary.com/dv4fxot90/image/upload/v1597220248/scp_images/long-horse_bz4je0.jpg',
            sound: 'https://res.cloudinary.com/dv4fxot90/video/upload/v1597221060/scp_sounds/long-horse_zxmatx.mp3',
        },
        {
            id: 4,
            name: 'Хороший мальчик',
            type: 'Волна 3 Опасные',
            keeping: 'Содержание',
            description: 'Монстр похожий на собаку с угольно-черным мехом и оскорбленным выражением лица. Голубоватые глаза без зрачков.',
            behavior: 'Скулит за дверью, ожидая, когда её откроют. Изредка похищает детей. Способен создавать цикличные измерения.',
            hazard: 'Средний',
            image: 'https://res.cloudinary.com/dv4fxot90/image/upload/v1597226295/scp_images/good-boy_gdxi7s.jpg',
            sound: 'https://res.cloudinary.com/dv4fxot90/video/upload/v1597226353/scp_sounds/good-boy_kxxjsr.mp3',
        },
        {
            id: 5,
            name: 'День 17',
            type: 'Волна 8 Городские душегубы',
            keeping: 'Невозможно, выдерживает даже попадание ядерного снаряда',
            description: 'Блуждающая Вера, часто называемая днем 17 - это гигантское существо черного цвета. ' +
                'Оно обладает длинной шеей скрывающуюся в облаках. По имеющейся информации его длина может достигать километра.',
            behavior: 'Появляется в бурю, разрушает здания. За день способен разрушить средний город полностью.',
            hazard: 'Очень высокий',
            image: 'https://res.cloudinary.com/dv4fxot90/image/upload/v1597231671/scp_images/day-17_m4slow.jpg',
            sound: 'https://res.cloudinary.com/dv4fxot90/video/upload/v1597231429/scp_sounds/day-17_hyxyx9.mp3',
        },
    ], [
        {
            id: 0,
            name: 'SCP-1-0',
            type: 'Тип',
            keeping: 'Содержание',
            description: 'Описание',
            behavior: 'Поведение',
            hazard: 'Класс опасности',
            image: 'https://res.cloudinary.com/dv4fxot90/image/upload/v1597133903/scp_images/SCP-106_qgkseo.jpg',
            sound: 'https://res.cloudinary.com/dv4fxot90/video/upload/v1597134877/scp_sounds/SCP-106_shvoiz.mp3',
        },
        {
            id: 1,
            name: 'SCP-1-1',
            type: 'Тип',
            keeping: 'Содержание',
            description: 'Описание',
            behavior: 'Поведение',
            hazard: 'Класс опасности',
            image: 'https://res.cloudinary.com/dv4fxot90/image/upload/v1597133903/scp_images/SCP-106_qgkseo.jpg',
            sound: 'https://res.cloudinary.com/dv4fxot90/video/upload/v1597134877/scp_sounds/SCP-106_shvoiz.mp3',
        },
        {
            id: 2,
            name: 'SCP-106 Старик',
            type: 'Кетер',
            keeping: 'Физическое взаимодействие с SCP-106 запрещено при любых обстоятельствах. ' +
            'SCP-106 следует содержать в герметичном контейнере, состоящем из сорока слоёв стали со свинцовым покрытием. ',
            description: 'SCP-106 выглядит как пожилой гуманоид на поздней стадии разложения. ' +
            'Внешность меняется от случая к случаю, но свойство "гнилости" присуще любому облику. ' +
            'SCP-106 не особо ловок, и временами лежит без движения по несколько дней, поджидая жертву. ' +
            'SCP-106 вызывает "разъедание" всех твёрдых поверхностей, к которым прикасается, ' +
            'физическое разложение материала начинается через несколько секунд после первого прикосновения. ' +
            'Внешне это проявляется как ржавление, гниение и растрескивание материала. Способен проходить сквозь твёрдые тела.',
            behavior: 'SCP-106 свойственны долгие периоды бездействия, во время которых он совершенно неподвижен. Из этого состояния SCP-106 мгновенно переходит в фазу активных действий, в ходе которой он атакует и похищает персонал и наносит значительный ущерб как своей камере содержания, так и всей Зоне. Протокол возврата [ДАННЫЕ УДАЛЕНЫ].' +
            'Похоже, что SCP-106 охотится не ради пропитания, а по прихоти. Во время фазы активных действия SCP-106 атакует и собирает много жертв, большинство из которых держит "живыми" в своём карманном измерении в течение длительного периода времени.' +
            '"Карманное измерение" SCP-106, похоже, доступно лишь ему самому. Устройства видеозаписи и передачи сигнала не теряют работоспособности в этом измерении, хотя качество записи и передаваемого сигнала очень сильно страдает. По некоторым сведениям, SCP-106 "играет" с пойманными жертвами, пользуясь полным контролем над пространством, временем и чувственным восприятием в пределах этого измерения. Похоже, также, что SCP-106 [ДАННЫЕ УДАЛЕНЫ].',
            hazard: 'Высокий',
            image: 'https://res.cloudinary.com/dv4fxot90/image/upload/v1597133903/scp_images/SCP-106_qgkseo.jpg',
            sound: 'https://res.cloudinary.com/dv4fxot90/video/upload/v1597134877/scp_sounds/SCP-106_shvoiz.mp3',
        },
        {
            id: 3,
            name: 'SCP-1-3',
            type: 'Тип',
            keeping: 'Содержание',
            description: 'Описание',
            behavior: 'Поведение',
            hazard: 'Класс опасности',
            image: 'https://res.cloudinary.com/dv4fxot90/image/upload/v1597133903/scp_images/SCP-106_qgkseo.jpg',
            sound: 'https://res.cloudinary.com/dv4fxot90/video/upload/v1597134877/scp_sounds/SCP-106_shvoiz.mp3',
        },
        {
            id: 4,
            name: 'SCP-1-4',
            type: 'Тип',
            keeping: 'Содержание',
            description: 'Описание',
            behavior: 'Поведение',
            hazard: 'Класс опасности',
            image: 'https://res.cloudinary.com/dv4fxot90/image/upload/v1597133903/scp_images/SCP-106_qgkseo.jpg',
            sound: 'https://res.cloudinary.com/dv4fxot90/video/upload/v1597134877/scp_sounds/SCP-106_shvoiz.mp3',
        },
        {
            id: 5,
            name: 'SCP-1-5',
            type: 'Тип',
            keeping: 'Содержание',
            description: 'Описание',
            behavior: 'Поведение',
            hazard: 'Класс опасности',
            image: 'https://res.cloudinary.com/dv4fxot90/image/upload/v1597133903/scp_images/SCP-106_qgkseo.jpg',
            sound: 'https://res.cloudinary.com/dv4fxot90/video/upload/v1597134877/scp_sounds/SCP-106_shvoiz.mp3',
        },
    ], [
        {
            id: 0,
            name: 'SCP-2-0',
            type: 'Тип',
            keeping: 'Содержание',
            description: 'Описание',
            behavior: 'Поведение',
            hazard: 'Класс опасности',
            image: 'https://res.cloudinary.com/dv4fxot90/image/upload/v1597133903/scp_images/SCP-106_qgkseo.jpg',
            sound: 'https://res.cloudinary.com/dv4fxot90/video/upload/v1597134877/scp_sounds/SCP-106_shvoiz.mp3',
        },
        {
            id: 1,
            name: 'SCP-2-1',
            type: 'Тип',
            keeping: 'Содержание',
            description: 'Описание',
            behavior: 'Поведение',
            hazard: 'Класс опасности',
            image: 'https://res.cloudinary.com/dv4fxot90/image/upload/v1597133903/scp_images/SCP-106_qgkseo.jpg',
            sound: 'https://res.cloudinary.com/dv4fxot90/video/upload/v1597134877/scp_sounds/SCP-106_shvoiz.mp3',
        },
        {
            id: 2,
            name: 'SCP-2-2',
            type: 'Тип',
            keeping: 'Содержание',
            description: 'Описание',
            behavior: 'Поведение',
            hazard: 'Класс опасности',
            image: 'https://res.cloudinary.com/dv4fxot90/image/upload/v1597133903/scp_images/SCP-106_qgkseo.jpg',
            sound: 'https://res.cloudinary.com/dv4fxot90/video/upload/v1597134877/scp_sounds/SCP-106_shvoiz.mp3',
        },
        {
            id: 3,
            name: 'SCP-2-3',
            type: 'Тип',
            keeping: 'Содержание',
            description: 'Описание',
            behavior: 'Поведение',
            hazard: 'Класс опасности',
            image: 'https://res.cloudinary.com/dv4fxot90/image/upload/v1597133903/scp_images/SCP-106_qgkseo.jpg',
            sound: 'https://res.cloudinary.com/dv4fxot90/video/upload/v1597134877/scp_sounds/SCP-106_shvoiz.mp3',
        },
        {
            id: 4,
            name: 'SCP-2-4',
            type: 'Тип',
            keeping: 'Содержание',
            description: 'Описание',
            behavior: 'Поведение',
            hazard: 'Класс опасности',
            image: 'https://res.cloudinary.com/dv4fxot90/image/upload/v1597133903/scp_images/SCP-106_qgkseo.jpg',
            sound: 'https://res.cloudinary.com/dv4fxot90/video/upload/v1597134877/scp_sounds/SCP-106_shvoiz.mp3',
        },
        {
            id: 5,
            name: 'SCP-2-5',
            type: 'Тип',
            keeping: 'Содержание',
            description: 'Описание',
            behavior: 'Поведение',
            hazard: 'Класс опасности',
            image: 'https://res.cloudinary.com/dv4fxot90/image/upload/v1597133903/scp_images/SCP-106_qgkseo.jpg',
            sound: 'https://res.cloudinary.com/dv4fxot90/video/upload/v1597134877/scp_sounds/SCP-106_shvoiz.mp3',
        },
    ], [
        {
            id: 0,
            name: 'SCP-3-0',
            type: 'Тип',
            keeping: 'Содержание',
            description: 'Описание',
            behavior: 'Поведение',
            hazard: 'Класс опасности',
            image: 'https://res.cloudinary.com/dv4fxot90/image/upload/v1597133903/scp_images/SCP-106_qgkseo.jpg',
            sound: 'https://res.cloudinary.com/dv4fxot90/video/upload/v1597134877/scp_sounds/SCP-106_shvoiz.mp3',
        },
        {
            id: 1,
            name: 'SCP-3-1',
            type: 'Тип',
            keeping: 'Содержание',
            description: 'Описание',
            behavior: 'Поведение',
            hazard: 'Класс опасности',
            image: 'https://res.cloudinary.com/dv4fxot90/image/upload/v1597133903/scp_images/SCP-106_qgkseo.jpg',
            sound: 'https://res.cloudinary.com/dv4fxot90/video/upload/v1597134877/scp_sounds/SCP-106_shvoiz.mp3',
        },
        {
            id: 2,
            name: 'SCP-3-2',
            type: 'Тип',
            keeping: 'Содержание',
            description: 'Описание',
            behavior: 'Поведение',
            hazard: 'Класс опасности',
            image: 'https://res.cloudinary.com/dv4fxot90/image/upload/v1597133903/scp_images/SCP-106_qgkseo.jpg',
            sound: 'https://res.cloudinary.com/dv4fxot90/video/upload/v1597134877/scp_sounds/SCP-106_shvoiz.mp3',
        },
        {
            id: 3,
            name: 'SCP-3-3',
            type: 'Тип',
            keeping: 'Содержание',
            description: 'Описание',
            behavior: 'Поведение',
            hazard: 'Класс опасности',
            image: 'https://res.cloudinary.com/dv4fxot90/image/upload/v1597133903/scp_images/SCP-106_qgkseo.jpg',
            sound: 'https://res.cloudinary.com/dv4fxot90/video/upload/v1597134877/scp_sounds/SCP-106_shvoiz.mp3',
        },
        {
            id: 4,
            name: 'SCP-3-4',
            type: 'Тип',
            keeping: 'Содержание',
            description: 'Описание',
            behavior: 'Поведение',
            hazard: 'Класс опасности',
            image: 'https://res.cloudinary.com/dv4fxot90/image/upload/v1597133903/scp_images/SCP-106_qgkseo.jpg',
            sound: 'https://res.cloudinary.com/dv4fxot90/video/upload/v1597134877/scp_sounds/SCP-106_shvoiz.mp3',
        },
        {
            id: 5,
            name: 'SCP-3-5',
            type: 'Тип',
            keeping: 'Содержание',
            description: 'Описание',
            behavior: 'Поведение',
            hazard: 'Класс опасности',
            image: 'https://res.cloudinary.com/dv4fxot90/image/upload/v1597133903/scp_images/SCP-106_qgkseo.jpg',
            sound: 'https://res.cloudinary.com/dv4fxot90/video/upload/v1597134877/scp_sounds/SCP-106_shvoiz.mp3',
        },
    ], [
        {
            id: 0,
            name: 'SCP-4-0',
            type: 'Тип',
            keeping: 'Содержание',
            description: 'Описание',
            behavior: 'Поведение',
            hazard: 'Класс опасности',
            image: 'https://res.cloudinary.com/dv4fxot90/image/upload/v1597133903/scp_images/SCP-106_qgkseo.jpg',
            sound: 'https://res.cloudinary.com/dv4fxot90/video/upload/v1597134877/scp_sounds/SCP-106_shvoiz.mp3',
        },
        {
            id: 1,
            name: 'SCP-4-1',
            type: 'Тип',
            keeping: 'Содержание',
            description: 'Описание',
            behavior: 'Поведение',
            hazard: 'Класс опасности',
            image: 'https://res.cloudinary.com/dv4fxot90/image/upload/v1597133903/scp_images/SCP-106_qgkseo.jpg',
            sound: 'https://res.cloudinary.com/dv4fxot90/video/upload/v1597134877/scp_sounds/SCP-106_shvoiz.mp3',
        },
        {
            id: 2,
            name: 'SCP-4-2',
            type: 'Тип',
            keeping: 'Содержание',
            description: 'Описание',
            behavior: 'Поведение',
            hazard: 'Класс опасности',
            image: 'https://res.cloudinary.com/dv4fxot90/image/upload/v1597133903/scp_images/SCP-106_qgkseo.jpg',
            sound: 'https://res.cloudinary.com/dv4fxot90/video/upload/v1597134877/scp_sounds/SCP-106_shvoiz.mp3',
        },
        {
            id: 3,
            name: 'SCP-4-3',
            type: 'Тип',
            keeping: 'Содержание',
            description: 'Описание',
            behavior: 'Поведение',
            hazard: 'Класс опасности',
            image: 'https://res.cloudinary.com/dv4fxot90/image/upload/v1597133903/scp_images/SCP-106_qgkseo.jpg',
            sound: 'https://res.cloudinary.com/dv4fxot90/video/upload/v1597134877/scp_sounds/SCP-106_shvoiz.mp3',
        },
        {
            id: 4,
            name: 'SCP-4-4',
            type: 'Тип',
            keeping: 'Содержание',
            description: 'Описание',
            behavior: 'Поведение',
            hazard: 'Класс опасности',
            image: 'https://res.cloudinary.com/dv4fxot90/image/upload/v1597133903/scp_images/SCP-106_qgkseo.jpg',
            sound: 'https://res.cloudinary.com/dv4fxot90/video/upload/v1597134877/scp_sounds/SCP-106_shvoiz.mp3',
        },
        {
            id: 5,
            name: 'SCP-4-5',
            type: 'Тип',
            keeping: 'Содержание',
            description: 'Описание',
            behavior: 'Поведение',
            hazard: 'Класс опасности',
            image: 'https://res.cloudinary.com/dv4fxot90/image/upload/v1597133903/scp_images/SCP-106_qgkseo.jpg',
            sound: 'https://res.cloudinary.com/dv4fxot90/video/upload/v1597134877/scp_sounds/SCP-106_shvoiz.mp3',
        },
    ], [
        {
            id: 0,
            name: 'SCP-5-0',
            type: 'Тип',
            keeping: 'Содержание',
            description: 'Описание',
            behavior: 'Поведение',
            hazard: 'Класс опасности',
            image: 'https://res.cloudinary.com/dv4fxot90/image/upload/v1597133903/scp_images/SCP-106_qgkseo.jpg',
            sound: 'https://res.cloudinary.com/dv4fxot90/video/upload/v1597134877/scp_sounds/SCP-106_shvoiz.mp3',
        },
        {
            id: 1,
            name: 'SCP-5-1',
            type: 'Тип',
            keeping: 'Содержание',
            description: 'Описание',
            behavior: 'Поведение',
            hazard: 'Класс опасности',
            image: 'https://res.cloudinary.com/dv4fxot90/image/upload/v1597133903/scp_images/SCP-106_qgkseo.jpg',
            sound: 'https://res.cloudinary.com/dv4fxot90/video/upload/v1597134877/scp_sounds/SCP-106_shvoiz.mp3',
        },
        {
            id: 2,
            name: 'SCP-5-2',
            type: 'Тип',
            keeping: 'Содержание',
            description: 'Описание',
            behavior: 'Поведение',
            hazard: 'Класс опасности',
            image: 'https://res.cloudinary.com/dv4fxot90/image/upload/v1597133903/scp_images/SCP-106_qgkseo.jpg',
            sound: 'https://res.cloudinary.com/dv4fxot90/video/upload/v1597134877/scp_sounds/SCP-106_shvoiz.mp3',
        },
        {
            id: 3,
            name: 'SCP-5-3',
            type: 'Тип',
            keeping: 'Содержание',
            description: 'Описание',
            behavior: 'Поведение',
            hazard: 'Класс опасности',
            image: 'https://res.cloudinary.com/dv4fxot90/image/upload/v1597133903/scp_images/SCP-106_qgkseo.jpg',
            sound: 'https://res.cloudinary.com/dv4fxot90/video/upload/v1597134877/scp_sounds/SCP-106_shvoiz.mp3',
        },
        {
            id: 4,
            name: 'SCP-5-4',
            type: 'Тип',
            keeping: 'Содержание',
            description: 'Описание',
            behavior: 'Поведение',
            hazard: 'Класс опасности',
            image: 'https://res.cloudinary.com/dv4fxot90/image/upload/v1597133903/scp_images/SCP-106_qgkseo.jpg',
            sound: 'https://res.cloudinary.com/dv4fxot90/video/upload/v1597134877/scp_sounds/SCP-106_shvoiz.mp3',
        },
        {
            id: 5,
            name: 'SCP-5-5',
            type: 'Тип',
            keeping: 'Содержание',
            description: 'Описание',
            behavior: 'Поведение',
            hazard: 'Класс опасности',
            image: 'https://res.cloudinary.com/dv4fxot90/image/upload/v1597133903/scp_images/SCP-106_qgkseo.jpg',
            sound: 'https://res.cloudinary.com/dv4fxot90/video/upload/v1597134877/scp_sounds/SCP-106_shvoiz.mp3',
        },
    ]];

export default scp;